# OpenSearch Configuration for KMRL Knowledge Hub

# Cluster settings
cluster.name: kmrl-cluster
node.name: kmrl-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings
discovery.type: single-node

# Memory settings
bootstrap.memory_lock: true

# Security settings (disabled for development)
plugins.security.disabled: true

# Index settings
action.auto_create_index: true

# Performance settings
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 10%

# Logging
logger.level: INFO
