import { Oswald } from "next/font/google";
import "./globals.css";



const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ["latin"],
});

export const metadata = {
    title: "Metro Link",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${oswald.variable} antialiased`} suppressHydrationWarning>
                    {children}
            </body>
        </html>
    );
}
